### ISSUE TITLE
Confidence Interal of EpiEStim app - identical for 75% & 25%

### ISSUE THREAD

**Issue by kcng802** [mrc-ide/EpiEstim#97] opened 2020-05-14 14:11 UTC
Dr. Robin Thomas asked me to submit this bug report.  There is an error in the EpiEstim app which causes the 75%  & 25% confidence intervals to show as identical.

t_start | t_end | Mean(R) | Std(R) | Quantile.0.025(R) | Quantile.0.05(R) | Quantile.0.25(R) | Median(R) | Quantile.0.75(R) | Quantile.0.95(R) | Quantile.0.975(R)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | 8 | 1.676272 | 0.976486 | 0.338931 | 0.449985 | 3.524117 | 1.492907 | 3.524117 | 3.524117 | 4.034139
3 | 9 | 2.584599 | 1.163681 | 0.839038 | 1.020117 | 4.750958 | 2.408954 | 4.750958 | 4.750958 | 5.33603
4 | 10 | 2.940135 | 1.134309 | 1.165467 | 1.355705 | 5.003363 | 2.791074 | 5.003363 | 5.003363 | 5.543205
5 | 11 | 2.29199 | 0.892125 | 0.902246 | 1.056114 | 3.929101 | 2.176504 | 3.929101 | 3.929101 | 4.352027
6 | 12 | 2.222825 | 0.803635 | 0.943369 | 1.096749 | 3.693079 | 2.123938 | 3.693079 | 3.693079 | 4.045335
7 | 13 | 2.13141 | 0.730564 | 0.960056 | 1.099175 | 3.455796 | 2.046818 | 3.455796 | 3.455796 | 3.792869
8 | 14 | 3.563511 | 0.88762 | 2.06355 | 2.251539 | 5.157335 | 3.483487 | 5.157335 | 5.157335 | 5.525408
9 | 15 | 2.845731 | 0.687544 | 1.678171 | 1.830796 | 4.07437 | 2.7868 | 4.07437 | 4.07437 | 4.353653
10 | 16 | 2.918638 | 0.626415 | 1.850218 | 1.98553 | 4.028234 | 2.865315 | 4.028234 | 4.028234 | 4.293019

**Comment by jstockwin** [comment] 2020-05-14 16:07
This is a duplicate of #88 which was fixed in #89

**Comment by kcng802** [comment] 2020-05-14 18:26
Thanks for your reply.  However, I was still getting the
output yesterday (May 13) which shows CI 75% &  25% identical.  I was
running the on-line app.  EpiEstim app.

KC Ng

**Comment by jstockwin** [comment] 2020-05-14 18:36
@kcng802 thanks for getting back to me.

That's because the version hasn't been updated yet...

I'll need to (1) get a new release of EpiEstim published, and then (2) update the version used by EpiEstimApp.

I'll try and do these ASAP, and then let you know

**Comment by jstockwin** [comment] 2020-05-29 16:24
@kcng802 the app has just been updated, so this should no longer be an issue. Thanks!

**Closed by jstockwin** 2020-05-29 16:24 UTC

**Comment by kcng802** [comment] 2020-05-31 17:32
Thank you so much!  I just tried and indeed the issue has been fixed

KC Ng
